# -------------------------------
# Deployment for web
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  strategy: {}
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: embarkx/tax-service-a:latest
          resources: {}
          env:
            - name: TAX_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: tax-config
                  key: TAX_SERVICE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: tax-config
                  key: PORT

---
# -------------------------------
# Service for web
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  type: NodePort
  selector:
    app: service-a
  ports:
    - port: 3000 # port exposed by the service
      targetPort: 3000 # port on the container
      nodePort: 32000 # port on the node
      # protocol: TCP
